### ISSUE TITLE
Variables For Update Frequency 

### ISSUE THREAD

**Issue by TrevorSchirmer** [ApolloAutomation/MSR-1#31]

**Comment by KidA001** [comment]
Hey, thanks for creating this feature request. I'll paste my details from discord here:

One thing I would love is to change the update interval of the sensors as a variable (both for the distance sensor and air sensor). In order to do this currently I'd have to copy the ESPHome code and manually change it in there, which then means I have to manually maintain that code now and copy any updates manually.

Some of these sensors update very frequently which can be nice in some use cases, but ends up with a lot of granularity (and DB Writes) that I don't need. I'd love to be able to set the update interval with some kind of input variable. Much appreciated!

**Comment by TrevorSchirmer** [comment]
@KidA001 Thank you very much for the addition here. I went back and forth but thought adding entities for all the sensors update frequency would clutter a little and confuse some. 


Instead I made sure they all had IDs, this will allow you or anyone to !extend them and change the frequency. For example see attached, I changed the ltr390's update frequency from the default 60s to 5s. Please let me know if you have any questions or suggestions how to better handle this.

`sensor:
  - platform: ltr390
    id: !extend ltr_390
    update_interval: 5s`


<img width="1641" alt="Screenshot 2024-02-20 at 11 32 44 PM" src="https://github.com/ApolloAutomation/MSR-1/assets/24777085/85f8f7f5-1d20-441c-87f8-cbb8dc8fe9b6">


-Trevor
