### ISSUE TITLE
Wi-Fi power_save_mode set to “none” 

### ISSUE THREAD

**Issue by neilmartin83** [ApolloAutomation/MSR-1#38]
Heya - this is more of a query than a problem.

I was wondering what the reasoning was for setting `power_save_mode: none`? Did you observe issues with the sensor or connectivity which needed this?

I tend to set this to `light` on all my ESP32 devices (it’s the default if not configured) and notice significantly lower running temps of the chip itself with no perceptible change of stability or performance.

Cheers! Loving this sensor.

**Comment by Bunton33** [comment]
Neil,

We appreciate your support and thanks for reaching out! We debated this and decided to go with none because we didn't want people to experience any connectivity issues. If users talked about the heat buildup then we would suggests them to use light to decrease the heat. We haven't heard of or experienced any connectivity issues on any setting. The best part is it's all open source and the community can do whatever they want. Thanks again for the kind words. We are always available if you need anything.

Best,
Justin Bunton
Apollo Automation

**Comment by TrevorSchirmer** [comment]
@neilmartin83 If you'd like help setting it to low power mode let us know and we can post a wiki article for it.
-Trevor

**Comment by neilmartin83** [comment]
Cheers @TrevorSchirmer - I've already set it up on my MSR-1, as well as enabling Bluetooth proxy and disabling the web server, but think a KB would be great for others! It's been rock solid for weeks.

Thank you.

**Comment by bharvey88** [comment]
solved wiki is now here https://wiki.apolloautomation.com/books/general/page/adjusting-wifi-power-save
