### ISSUE TITLE
ota upgrades not working -  'ota' requires a 'platform' key but it was not specified.

### ISSUE THREAD

**Issue by thomaslunze** [ApolloAutomation/MSR-1#40]
please include this for enabling future upgrades via ota:
https://esphome.io/components/ota.html

INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/wohnzimmer-presence2.yaml...
Failed config

ota.unknown: [source /data/packages/8b3d0215/Integrations/ESPHome/MSR-1.yaml:83]
  
  'ota' requires a 'platform' key but it was not specified.
  password: apolloautomation
  safe_mode: False

**Comment by bharvey88** [comment]
> please include this for enabling future upgrades via ota: https://esphome.io/components/ota.html
> 
> INFO ESPHome 2024.6.1 INFO Reading configuration /config/esphome/wohnzimmer-presence2.yaml... Failed config
> 
> ota.unknown: [source /data/packages/8b3d0215/Integrations/ESPHome/MSR-1.yaml:83]
> 
> 'ota' requires a 'platform' key but it was not specified. password: apolloautomation safe_mode: False

There were two breaking changes to esphome and we're in the process of getting the yaml updated on the github repos for each device so that your updates will succeed. For now the easy answer is to not upgrade and wait for us to update our end. Once that's done, you should be able to validate and then install in esphome dashboard and the upgrade should then succeed. There are no benefits to upgrading to 2024.6.1 at this time.

**Comment by TrevorSchirmer** [comment]
@thomaslunze Thanks for the issue. The correction has been merged but it will take about 24 hours for your ESPHome to clear the cache
